settings:
  language: ru
  db_url: sqlite:///hotspot.db  # OPTIONAL. Url for connect database use SQLAlchemy URL, by default used sqlite db, file created after start in config directory
  cache_url: memcached+unix:///var/run/memcached.sock # OPTIONAL. Url for connect cache use URL, by default used in-memory cache
  debug: true  # Enable debug mode
  log_level: DEBUG  # Enable debug mode
  secret_key: OmegaSecret
  admin:
    username: admin
    password: admin  # Default password is admin
    max_login_attempts: 5
    lockut_time: 300 # Seconds
  hotspot_users:
    guest:
      password: secret
      delay: 24h  # Hours. You can use suffixes such as: w, d, m, s. Without a suffix, the default is hours.
    staff:
      password: supersecret
      delay: 30d  # Days. You can use suffixes such as: w, d, m, s. Without a suffix, the default is hours.
  sender:
    type: smsru
    api_key: YOUR-API-KEY  # Setup your api key
  radius:
    enabled: true
    addresses:
      - 0.0.0.0
    ports:
      auth: 1812
      acct: 1813
      CoA: 3799
    hosts: !import hosts.yaml